export const BASE_DIMENSION = 8;

// export const DEFAULT_GRID_ROW_HEIGHT = BASE_DIMENSION * 6;
export const DEFAULT_GRID_ROW_HEIGHT = 50;
export const MINIMUM_GRID_ROW_HEIGHT = DEFAULT_GRID_ROW_HEIGHT / 2;

// export const DEFAULT_GRID_COLUMN_WIDTH = BASE_DIMENSION * 8;
export const DEFAULT_GRID_COLUMN_WIDTH = 60;
export const MIN_GRID_COLUMN_WIDTH = 20;

export const DEFAULT_TEXT_SIZE = BASE_DIMENSION * 1.5;

export const DEFAULT_STROKE_WIDTH = 1;
